unbind C-b
set -g prefix C-end
set -s escape-time 1
set -g base-index 1
set -g mouse on
bind -n M-j 'select-pane -t :.+'
bind -n M-k 'select-pane -t :.-'
bind -n M-> 'rotate-window -D; select-pane -t 0;select-layout main-horizontal;resize-pane -t :.0 -y 85%'
bind -n M-< 'rotate-window -U; select-pane -t 0;select-layout main-horizontal;resize-pane -t :.0 -y 85%'
bind -n M-c 'kill-pane;select-layout main-horizontal;resize-pane -t :.0 -y 85%'
bind -n M-w 'split-window -t :.0; swap-pane -s :.0 -t :.1;select-layout main-horizontal;resize-pane -t :.0 -y 85%'
bind -n M-n 'split-window -t :.0 -c "#{pane_current_path}"; swap-pane -s :.0 -t :.1;select-layout main-horizontal;resize-pane -t :.0 -y 85%'
bind -n M-Enter 'swap-pane -s :. -t :.0; select-pane -t :.0'
bind -n M-f 'resize-pane -Z'
bind -n M-r source-file ~/.tmux.conf
set -g status off
bind -n M-y 'copy-mode'
bind -T copy-mode-vi v send -X 'begin-selection'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
set-option -g focus-events on
set -g default-terminal "xterm-256color"
