set -s escape-time 1
set -g base-index 1
set -g mouse on
bind j 'select-pane -t :.+'
bind k 'select-pane -t :.-'
bind , 'rotate-window -D; select-pane -t 0;select-layout main-vertical;resize-pane -t :.0 -x 65%'
bind . 'rotate-window -U; select-pane -t 0;select-layout main-vertical;resize-pane -t :.0 -x 65%'
bind c 'kill-pane;select-layout main-vertical;resize-pane -t :.0 -x 65%'
bind w 'split-window -t :.0; swap-pane -s :.0 -t :.1;select-layout main-vertical;resize-pane -t :.0 -x 65%'
bind n 'split-window -t :.0 -c "#{pane_current_path}"; swap-pane -s :.0 -t :.1;select-layout main-vertical;resize-pane -t :.0 -x 65%'
bind o 'swap-pane -s :. -t :.0; select-pane -t :.0'
bind f 'resize-pane -Z'
bind r source-file ~/.tmux.conf
set -g status off
bind y 'copy-mode'
set-option -g focus-events on
set -g default-terminal "xterm-256color"
setw -g mode-keys vi
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
