#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

status () {
  echo -n " $(date '+%m/%d/%Y ')$(date '+%r' | awk '{print $1}' | sed s/:[0-9][0-9]$//) $(date '+%r' | awk '{print $2}') "
}

updateStatus () {
  while :; do
    xsetroot -name "$(status)"
    sleep 0.1
  done
}

xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 144 --right-of DVI-D-1
updateStatus &
~/.fehbg &
compton --no-fading-openclose &
discord &
xrdb ~/.Xresources
exec dwm
