set -g base-index 1
set -s escape-time 0
set -g mouse on
bind -n M-j 'select-pane -t :.+;select-layout main-vertical'
bind -n M-k 'select-pane -t :.-;select-layout main-vertical'
bind -n M-> 'rotate-window -D; select-pane -t 0;select-layout main-vertical'
bind -n M-< 'rotate-window -U; select-pane -t 0;select-layout main-vertical'
bind -n M-c 'kill-pane;select-layout main-vertical'
bind -n M-n 'split-window -t :.0; swap-pane -s :.0 -t :.1;select-layout main-vertical'
bind -n M-w 'split-window -t :.0 -c "#{pane_current_path}"; swap-pane -s :.0 -t :.1;select-layout main-vertical'
bind -n M-Enter 'swap-pane -s :. -t :.0; select-pane -t :.0'
bind -n M-Space 'resize-pane -Z'
bind r source-file ~/.tmux.conf
#setw -g mode-keys vi
set -g status off
#set -g status-interval 1
#set -g status-justify centre
#set -g status-keys vi
#set -g status-position top
#set -g status-style fg=colour136,bg="#002b36"
#set -g status-left-length 60
#set -g status-left-style default
#set -g status-left "#[fg=green] #S #[default]"
#set -g status-right-length 60
#set -g status-right-style default
#set -g status-right "#[fg=green] %l:%M %p #[default]"
#set -g window-status-style fg=colour244,bg=default
#set -g window-status-format ' #I #W '
#set -g window-status-current-style fg=black,bg=colour136
#set -g window-status-current-format ' #I #W '
